#! /bin/bash
#  by Andrew Velez
#
#  Bash functions namespaced with my initials av (a-to-v; just short of everything)

prepend_path() {
  local var_name="$1"
  shift
  local current="${!var_name}"
  local new_paths=""

  for dir in "$@"; do
    [ ! -d "$dir" ] && continue
    [[ ":$current:" == *":$dir:"* ]] && continue
    [[ ":$new_paths:" == *":$dir:"* ]] && continue

    new_paths="$dir${new_paths:+:$new_paths}"
  done

  [ -n "$new_paths" ] && {
    if [ -z "$current" ]; then
      printf -v "$var_name" '%s' "$new_paths"
    else
      printf -v "$var_name" '%s' "$new_paths:$current"
    fi
  }
}

edit-file() {
  (code-oss -r "$@" &) > /dev/null 2>&1
}

view-logs() {
  local _logfile="${1:-/var/log/socklog/everything/current}"
  local _numlines="${2:-5000}"
  local _optgrep="${3}"

  if [[ -z "${_optgrep}" ]]; then
    tail -n "${_numlines}" "${_logfile}" | tac | bat -l log
  else
    tail -n "${_numlines}" "${_logfile}" | tac | grep -F "${_optgrep}" | bat -l log
  fi
}
export -f view-logs

# Source - https://stackoverflow.com/a
# Posted by Rucent88
# Retrieved 2025-12-24, License - CC BY-SA 4.0
ssudo() {
  [[ "$(type -t "$1")" == "function" ]] \
    && ARGS="$*" && sudo bash -c "$(declare -f "$1"); $ARGS"
}
alias ssudo="ssudo "
