#! /bin/bash
#  by Andrew Velez

# aliases
alias ls='ls --color=auto'
alias l='ls -Al'
alias ll='ls -AlL'
alias where='whereis'
alias sudo='sudo '
alias e='edit-file'

# void linux
alias vinstall='xbps-install -S'
alias vsearch='xbps-query -Rs'
alias vremove='xbps-remove'
alias vupgrade='xbps-install -Su; flatpak update'

# directory shortcuts
alias ph='cd $HOME; clear'

# dinit
alias dinit-system='dinitctl --system --socket-path /run/dinitctl '
alias dinits='dinit-system'
