#! /bin/bash
#  by: Andrew Velez
#
#  desc: brought in from the rain

contains_substring() (
  case "$1" in
    *"$2"*) return 0 ;;
    *) return 1 ;;
  esac
)

prepend_dir_to() {
  if [ -z "$1" ] || ! [ -d "$2" ]; then
    return 1
  fi

  if ! contains_substring ":${!1}:" ":${2}:"; then
    eval "$1=\"${2}:${!1}\""
  fi
}

edit-file() {
  /bin/code-oss "$@" > /dev/null 2>&1
}

view-logs() {
  local _logfile="${1:-/var/log/socklog/everything/current}"
  local _numlines="${2:-5000}"
  local _optgrep="${3}"

  if [[ -z ${_optgrep} ]]; then
    tail -n "${_numlines}" "${_logfile}" | tac | bat -l log
  else
    tail -n "${_numlines}" "${_logfile}" | tac | grep -F "${_optgrep}" | bat -l log
  fi
}
export -f view-logs

# Source - https://stackoverflow.com/a
# Posted by Rucent88
# Retrieved 2025-12-24, License - CC BY-SA 4.0
doas_plus() {
  [[ "$(type -t "$1")" == "function" ]] && doas bash -c "$(declare -f "$1"); $*"
}
alias doas_plus="doas_plus "
