#! /bin/bash
#  by Andrew Velez

# aliases
alias ls='ls --color=auto'
alias l='ls -Al'
alias ll='ls -AlL'
alias where='whereis'
alias sudo='sudo '
alias e='edit-file'

# directory shortcuts
alias ph='cd $HOME; clear'

# void specific
alias vadd='sudo xbps-install -S '
alias vfind='sudo xbps-query -Rs '
alias vdel='sudo xbps-remove '
alias vupgrade='sudo xbps-install -Su; flatpak update'

alias services='sudo sv status /var/service/*'
