#! /bin/bash
#  by Andrew Velez

# aliases
alias ls='ls --color=auto'
alias l='ls -Al'
alias ll='ls -AlL'
alias where='whereis'
alias doas='doas '
alias e='edit-file'

# directory shortcuts
alias ph='cd $HOME; clear'

# chimera specific
alias cadd='doas apk update; doas apk add '
alias cfind='doas apk update; doas apk search '
alias cupgrade='doas apk update; doas apk upgrade; flatpak update '
alias cdel='doas apk update; doas apk del '
